import { Location, ServiceType } from "@/types/dlni";

export const locationsData: Record<ServiceType, Location[]> = {
  "دورات المياه": [
    {
      id: "bathroom-east-gf",
      name: "دورة المياه الشرقية - الدور الأرضي",
      description: "دورة مياه حديثة مع مرافق للوضوء، تتسع لـ 50 شخص",
      distance: 0,
      direction: "",
      lat: 24.468,
      lng: 39.6115,
      floor: "الدور الأرضي",
      capacity: "50 شخص",
      features: ["مكيفة", "مرافق وضوء", "إمكانية وصول للمعاقين"],
      openingHours: "24 ساعة",
      crowdLevel: "متوسط",
    },
    {
      id: "bathroom-west-gf",
      name: "دورة المياه الغربية - الدور الأرضي",
      description: "دورة مياه واسعة مع خدمات متكاملة ومرافق عوائل",
      distance: 0,
      direction: "",
      lat: 24.467,
      lng: 39.6105,
      floor: "الدور الأرضي",
      capacity: "80 شخص",
      features: ["مرافق عائلية", "غرف تغيير", "مكيفة"],
      openingHours: "24 ساعة",
      crowdLevel: "منخفض",
    },
    {
      id: "bathroom-north-1f",
      name: "دورة المياه الشمالية - الدور الأول",
      description: "دورة مياه في الدور الأول مع إطلالة على الحرم",
      distance: 0,
      direction: "",
      lat: 24.469,
      lng: 39.611,
      floor: "الدور الأول",
      capacity: "40 شخص",
      features: ["إطلالة جميلة", "مكيفة", "هادئة"],
      openingHours: "24 ساعة",
      crowdLevel: "منخفض",
    },
    {
      id: "bathroom-south-gf",
      name: "دورة المياه الجنوبية - الدور الأرضي",
      description: "دورة مياه قريبة من المداخل الرئيسية",
      distance: 0,
      direction: "",
      lat: 24.466,
      lng: 39.6108,
      floor: "الدور الأرضي",
      capacity: "60 شخص",
      features: ["قرب المداخل", "مكيفة", "إضاءة ممتازة"],
      openingHours: "24 ساعة",
      crowdLevel: "مرتفع",
    },
    {
      id: "bathroom-center-2f",
      name: "دورة المياه الوسطى - الدور الثاني",
      description: "دورة مياه هادئة في الدور الثاني",
      distance: 0,
      direction: "",
      lat: 24.4675,
      lng: 39.6112,
      floor: "الدور الثاني",
      capacity: "30 شخص",
      features: ["هادئة", "مكيفة", "نظافة عالية"],
      openingHours: "24 ساعة",
      crowdLevel: "منخفض",
    },
    {
      id: "bathroom-family-women",
      name: "دورة المياه للعوائل - منطقة النساء",
      description: "دورة مياه مخصصة للعائلات في قسم النساء",
      distance: 0,
      direction: "",
      lat: 24.4685,
      lng: 39.6108,
      floor: "الدور الأرضي",
      capacity: "40 شخص",
      features: ["مخصصة للعائلات", "خصوصية عالية", "مرافق أطفال"],
      openingHours: "24 ساعة",
      crowdLevel: "متوسط",
    },
  ],

  "أماكن الوضوء": [
    {
      id: "wudu-main-gf",
      name: "مكان الوضوء الرئيسي - الدور الأرضي",
      description: "مكان وضوء كبير مع 100 صنبور ومياه مفلترة",
      distance: 0,
      direction: "",
      lat: 24.4685,
      lng: 39.6118,
      floor: "الدور الأرضي",
      capacity: "100 شخص",
      features: ["مياه مفلترة", "100 صنبور", "تدفئة شتوية"],
      openingHours: "24 ساعة",
      crowdLevel: "مرتفع",
    },
    {
      id: "wudu-east-1f",
      name: "مكان الوضوء الشرقي - الدور الأول",
      description: "مكان وضوء هادئ مع إطلالة شرقية",
      distance: 0,
      direction: "",
      lat: 24.467,
      lng: 39.6102,
      floor: "الدور الأول",
      capacity: "60 شخص",
      features: ["هادئ", "إطلالة جميلة", "تهوية طبيعية"],
      openingHours: "24 ساعة",
      crowdLevel: "منخفض",
    },
    {
      id: "wudu-west-1f",
      name: "مكان الوضوء الغربي - الدور الأول",
      description: "مكان وضوء حديث مع تقنيات توفير المياه",
      distance: 0,
      direction: "",
      lat: 24.469,
      lng: 39.6125,
      floor: "الدور الأول",
      capacity: "70 شخص",
      features: ["توفير المياه", "حديث", "مكيف"],
      openingHours: "24 ساعة",
      crowdLevel: "متوسط",
    },
    {
      id: "wudu-family-women",
      name: "مكان الوضوء للعوائل - منطقة النساء",
      description: "مكان وضوء مخصص للعائلات مع خصوصية كاملة",
      distance: 0,
      direction: "",
      lat: 24.4688,
      lng: 39.6105,
      floor: "الدور الأرضي",
      capacity: "50 شخص",
      features: ["خصوصية كاملة", "مرافق أطفال", "مكيف"],
      openingHours: "24 ساعة",
      crowdLevel: "منخفض",
    },
    {
      id: "wudu-north-2f",
      name: "مكان الوضوء الشمالي - الدور الثاني",
      description: "مكان وضوء هادئ في الدور الثاني",
      distance: 0,
      direction: "",
      lat: 24.4692,
      lng: 39.6115,
      floor: "الدور الثاني",
      capacity: "40 شخص",
      features: ["هادئ جداً", "مكيف", "نظافة فائقة"],
      openingHours: "24 ساعة",
      crowdLevel: "منخفض",
    },
    {
      id: "wudu-south-basement",
      name: "مكان الوضوء الجنوبي - القبو",
      description: "مكان وضوء في القبو مع برودة طبيعية",
      distance: 0,
      direction: "",
      lat: 24.4665,
      lng: 39.611,
      floor: "القبو",
      capacity: "80 شخص",
      features: ["برودة طبيعية", "واسع", "هادئ"],
      openingHours: "24 ساعة",
      crowdLevel: "منخفض",
    },
  ],

  الطواف: [
    {
      id: "tawaf-main-entrance",
      name: "مدخل الطواف الرئيسي - باب الملك فهد",
      description: "المدخل الرئيسي للطواف مع مرافق كاملة وإرشاد",
      distance: 0,
      direction: "",
      lat: 24.4675,
      lng: 39.611,
      floor: "الدور الأرضي",
      capacity: "آلاف الأشخاص",
      features: ["مرافق كاملة", "إرشاد متوفر", "مكيف"],
      openingHours: "24 ساعة",
      crowdLevel: "مرتفع جداً",
    },
    {
      id: "tawaf-wheelchair",
      name: "مدخل الطواف للعجلات - مخصص للمعاقين",
      description: "مدخل مخصص لذوي الاحتياجات الخاصة والعجلات المتحركة",
      distance: 0,
      direction: "",
      lat: 24.468,
      lng: 39.6108,
      floor: "الدور الأرضي",
      capacity: "مخصص للمعاقين",
      features: ["مخصص للمعاقين", "مصاعد", "مرافق خاصة"],
      openingHours: "24 ساعة",
      crowdLevel: "منخفض",
    },
    {
      id: "tawaf-waiting",
      name: "منطقة انتظار الطواف - صالة الانتظار",
      description: "منطقة مكيفة لانتظار دور الطواف",
      distance: 0,
      direction: "",
      lat: 24.467,
      lng: 39.6112,
      floor: "الدور الأرضي",
      capacity: "500 شخص",
      features: ["مكيفة", "مقاعد مريحة", "شاشات إرشادية"],
      openingHours: "24 ساعة",
      crowdLevel: "متوسط",
    },
  ],

  السعي: [
    {
      id: "sai-start",
      name: "بداية مسار السعي - الصفا",
      description: "نقطة البداية الرسمية لمسار السعي من الصفا",
      distance: 0,
      direction: "",
      lat: 24.4688,
      lng: 39.6118,
      floor: "الدور الأرضي",
      capacity: "مفتوح",
      features: ["نقطة البداية", "لوحات إرشادية", "مكيف"],
      openingHours: "24 ساعة",
      crowdLevel: "مرتفع",
    },
    {
      id: "sai-rest1",
      name: "نقطة الراحة الأولى - منتصف المسار",
      description: "منطقة راحة مكيفة في منتصف مسار السعي",
      distance: 0,
      direction: "",
      lat: 24.4685,
      lng: 39.6122,
      floor: "الدور الأرضي",
      capacity: "200 شخص",
      features: ["مكيفة", "مقاعد", "مياه باردة"],
      openingHours: "24 ساعة",
      crowdLevel: "متوسط",
    },
    {
      id: "sai-rest2",
      name: "نقطة الراحة الثانية - قرب المروة",
      description: "منطقة راحة أخيرة قبل الوصول للمروة",
      distance: 0,
      direction: "",
      lat: 24.4682,
      lng: 39.6125,
      floor: "الدور الأرضي",
      capacity: "150 شخص",
      features: ["قرب النهاية", "مكيفة", "خدمات طبية"],
      openingHours: "24 ساعة",
      crowdLevel: "متوسط",
    },
  ],

  "مكاتب الإرشاد": [
    {
      id: "guidance-main",
      name: "مكتب الإرشاد الرئيسي - المدخل الرئيسي",
      description: "مكتب الإرشاد الرئيسي مع خدمات شاملة ومترجمين",
      distance: 0,
      direction: "",
      lat: 24.4678,
      lng: 39.6115,
      floor: "الدور الأرضي",
      capacity: "خدمة مستمرة",
      features: ["مترجمين", "خرائط", "معلومات شاملة"],
      openingHours: "24 ساعة",
      crowdLevel: "مرتفع",
    },
    {
      id: "guidance-secondary",
      name: "مكتب الإرشاد الفرعي - الجانب الغربي",
      description: "مكتب إرشاد فرعي مع خدمات أساسية",
      distance: 0,
      direction: "",
      lat: 24.467,
      lng: 39.6105,
      floor: "الدور الأرضي",
      capacity: "خدمة مستمرة",
      features: ["خدمات أساسية", "خرائط", "توجيه سريع"],
      openingHours: "24 ساعة",
      crowdLevel: "متوسط",
    },
    {
      id: "guidance-hajj",
      name: "مكتب معلومات الحج والعمرة",
      description: "مكتب مختص بمعلومات الحج والعمرة وإجراءاتها",
      distance: 0,
      direction: "",
      lat: 24.469,
      lng: 39.612,
      floor: "الدور الأول",
      capacity: "خدمة مستمرة",
      features: ["معلومات الحج", "إجراءات", "استشارات"],
      openingHours: "06:00 - 24:00",
      crowdLevel: "متوسط",
    },
  ],

  الحلاقة: [
    {
      id: "barber-1",
      name: "محل الحلاقة الأول - للرجال",
      description: "محل حلاقة حديث مع معدات متطورة",
      distance: 0,
      direction: "",
      lat: 24.4675,
      lng: 39.6108,
      floor: "الدور الأرضي",
      capacity: "10 كراسي",
      features: ["معدات حديثة", "مكيف", "نظافة عالية"],
      openingHours: "05:00 - 02:00",
      crowdLevel: "مرتفع",
    },
    {
      id: "barber-2",
      name: "محل الحلاقة الثاني - للرجال",
      description: "محل حلاقة إضافي لتقليل الانتظار",
      distance: 0,
      direction: "",
      lat: 24.468,
      lng: 39.6112,
      floor: "الدور الأرضي",
      capacity: "8 كراسي",
      features: ["سرعة في الخدمة", "مكيف", "أسعار مناسبة"],
      openingHours: "05:00 - 02:00",
      crowdLevel: "متوسط",
    },
    {
      id: "barber-women",
      name: "محل الحلاق�� النسائي - للنساء",
      description: "محل حلاقة مخصص للنساء مع خصوصية كاملة",
      distance: 0,
      direction: "",
      lat: 24.467,
      lng: 39.611,
      floor: "الدور الأول",
      capacity: "6 كراسي",
      features: ["خصوصية كاملة", "محجبات", "خدمة نسائية"],
      openingHours: "08:00 - 23:00",
      crowdLevel: "منخفض",
    },
  ],

  "مكاتب الأمانات": [
    {
      id: "storage-1",
      name: "مكتب الأمانات الرئيسي - الدور الأرضي",
      description: "مكتب أمانات آمن مع تقنيات حديثة للحفظ",
      distance: 0,
      direction: "",
      lat: 24.4682,
      lng: 39.6118,
      floor: "الدور الأرضي",
      capacity: "1000 خزانة",
      features: ["آمن", "مراقبة 24/7", "تأمين شامل"],
      openingHours: "24 ساعة",
      crowdLevel: "مرتفع",
    },
    {
      id: "storage-2",
      name: "مكتب الأمانات الفرعي - الدور الأول",
      description: "مكتب أمانات إض��في للمتعلقات الصغيرة",
      distance: 0,
      direction: "",
      lat: 24.467,
      lng: 39.6105,
      floor: "الدور الأول",
      capacity: "500 خزانة",
      features: ["للمتعلقات الصغيرة", "سريع", "آمن"],
      openingHours: "24 ساعة",
      crowdLevel: "متوسط",
    },
  ],

  "مخارج الطوارئ": [
    {
      id: "emergency-east",
      name: "مخرج الطوارئ الشرقي - الباب الشرقي",
      description: "مخرج طوارئ رئيسي مع إمكانية وصول سريع للخارج",
      distance: 0,
      direction: "",
      lat: 24.469,
      lng: 39.612,
      floor: "جميع الأدوار",
      capacity: "آلاف الأشخاص",
      features: ["وصول سريع", "إضاءة طوارئ", "عرض واسع"],
      openingHours: "24 ساعة",
      crowdLevel: "حسب الحاجة",
    },
    {
      id: "emergency-west",
      name: "مخرج الطوارئ الغربي - الباب الغربي",
      description: "مخرج طوارئ غربي مع تجهيزات إسعافية",
      distance: 0,
      direction: "",
      lat: 24.467,
      lng: 39.61,
      floor: "جميع الأدوار",
      capacity: "آلاف الأشخاص",
      features: ["تجهيزات إسعافية", "إضاءة طوارئ", "مسار آمن"],
      openingHours: "24 ساعة",
      crowdLevel: "حسب الحاجة",
    },
    {
      id: "emergency-north",
      name: "مخرج الطوارئ الشمالي - الباب الشمالي",
      description: "مخرج طوارئ شمالي مع وصول للمواقف",
      distance: 0,
      direction: "",
      lat: 24.47,
      lng: 39.611,
      floor: "جميع الأدوار",
      capacity: "آلاف الأشخاص",
      features: ["وصول للمواقف", "مسار واضح", "آمن"],
      openingHours: "24 ساعة",
      crowdLevel: "حسب الحاجة",
    },
    {
      id: "emergency-south",
      name: "مخرج الطوارئ الجنوبي - الباب الجنوبي",
      description: "مخرج طوارئ جنوبي قريب من المحطات",
      distance: 0,
      direction: "",
      lat: 24.466,
      lng: 39.611,
      floor: "جميع الأدوار",
      capacity: "آلاف الأشخاص",
      features: ["قريب من المحطات", "مسار آمن", "إرشاد واضح"],
      openingHours: "24 ساعة",
      crowdLevel: "حسب الحاجة",
    },
  ],

  "مياه زمزم": [
    {
      id: "zamzam-main",
      name: "نقطة توزيع زمزم الرئيسية - القبو",
      description: "المصدر الرئيسي لمياه زمزم مع برادات متعددة",
      distance: 0,
      direction: "",
      lat: 24.4683,
      lng: 39.6116,
      floor: "القبو",
      capacity: "آلاف الليترات",
      features: ["مصدر رئيسي", "برادات متعددة", "نظافة فائقة"],
      openingHours: "24 ساعة",
      crowdLevel: "مرتفع",
    },
    {
      id: "zamzam-secondary",
      name: "نقطة توزيع زمزم الفرعية - الدور الأرضي",
      description: "نقطة توزيع فرعية للحصول السريع على المياه",
      distance: 0,
      direction: "",
      lat: 24.467,
      lng: 39.6108,
      floor: "الدور الأرضي",
      capacity: "مئات الليترات",
      features: ["وصول سريع", "برادات", "تعبئة مجانية"],
      openingHours: "24 ساعة",
      crowdLevel: "متوسط",
    },
  ],

  "الروضة الشريفة": [
    {
      id: "rawdah-men",
      name: "مدخل الروضة الشريفة للرجال",
      description: "المدخل المخصص للرجال للروضة الشريفة المباركة",
      distance: 0,
      direction: "",
      lat: 24.4685,
      lng: 39.612,
      floor: "الدور الأرضي",
      capacity: "محدود بالوقت",
      features: ["مقدس", "تنظيم دخول", "محدود بالوقت"],
      openingHours: "حسب البرنامج",
      crowdLevel: "مرتفع جداً",
    },
    {
      id: "rawdah-women",
      name: "مدخل الروضة الشريفة للنساء",
      description: "المدخل المخصص للنساء للروضة الشريفة المباركة",
      distance: 0,
      direction: "",
      lat: 24.4688,
      lng: 39.6118,
      floor: "الدور الأرضي",
      capacity: "محدود بالوقت",
      features: ["مقدس", "خصوصية", "تنظيم خاص"],
      openingHours: "حسب البرنامج",
      crowdLevel: "مرتفع جداً",
    },
  ],

  "ذوي الاحتياجات الخاصة": [
    {
      id: "disabled-elevator",
      name: "مصعد ذوي الاحتياجات الخاصة - المدخل الرئيسي",
      description: "مصعد واسع مخصص للكراسي المتحركة وذوي الاحتياجات",
      distance: 0,
      direction: "",
      lat: 24.4675,
      lng: 39.6115,
      floor: "جميع الأدوار",
      capacity: "8 أشخاص",
      features: ["واسع", "آمن", "سهل الاستخدام"],
      openingHours: "24 ساعة",
      crowdLevel: "منخفض",
    },
    {
      id: "disabled-facilities",
      name: "مرافق خ��صة للمعاقين - الدور الأرضي",
      description: "مرافق متكاملة مع دورات مياه ومناطق راحة",
      distance: 0,
      direction: "",
      lat: 24.468,
      lng: 39.611,
      floor: "الدور الأرضي",
      capacity: "20 شخص",
      features: ["متكاملة", "مريحة", "خصوصية"],
      openingHours: "24 ساعة",
      crowdLevel: "منخفض",
    },
    {
      id: "disabled-parking",
      name: "مواقف مخصصة للمعاقين - موقف رقم 1",
      description: "مواقف قريبة من المداخل مع ممرات آمنة",
      distance: 0,
      direction: "",
      lat: 24.466,
      lng: 39.609,
      floor: "الدور الأرضي",
      capacity: "50 سيارة",
      features: ["قريبة من المداخل", "ممرات آمنة", "مجانية"],
      openingHours: "24 ساعة",
      crowdLevel: "منخفض",
    },
  ],

  "المطاعم والكافيتريات": [
    {
      id: "restaurant-haramain",
      name: "مطعم الحرمين - الطعام التقليدي",
      description: "مطعم يقدم الأطعمة التقليدية والعربية الأصيلة",
      distance: 0,
      direction: "",
      lat: 24.469,
      lng: 39.6125,
      floor: "الدور الثاني",
      capacity: "200 شخص",
      features: ["طعام تقليدي", "حلال 100%", "أسعار مناسبة"],
      openingHours: "24 ساعة",
      crowdLevel: "مرتفع",
    },
    {
      id: "cafeteria-diafa",
      name: "كافيتريا الضيافة - المشروبات والوجبات الخفيفة",
      description: "كافيتريا تقدم المشروبات الساخنة والباردة",
      distance: 0,
      direction: "",
      lat: 24.467,
      lng: 39.6105,
      floor: "الدور الأول",
      capacity: "100 شخص",
      features: ["مشروبات متنوعة", "وجبات خفيفة", "سريع"],
      openingHours: "24 ساعة",
      crowdLevel: "متوسط",
    },
    {
      id: "cafe-madinah",
      name: "مقهى المدينة - القهوة والحلويات",
      description: "مقهى عصري يقدم القهوة العربية والحلويات",
      distance: 0,
      direction: "",
      lat: 24.468,
      lng: 39.6115,
      floor: "الدور الأول",
      capacity: "80 شخص",
      features: ["قهوة عربية", "حلويات", "أجواء هادئة"],
      openingHours: "06:00 - 24:00",
      crowdLevel: "متوسط",
    },
  ],

  الصيدليات: [
    {
      id: "pharmacy-main",
      name: "صيدلية الحرم الرئيسية - أدوية شاملة",
      description: "صيدلية كاملة مع جميع الأدوية والمستلزمات الطبية",
      distance: 0,
      direction: "",
      lat: 24.4675,
      lng: 39.611,
      floor: "الدور الأرضي",
      capacity: "خدمة مستمرة",
      features: ["أدوية شاملة", "استشارة طبية", "متوفرة دائماً"],
      openingHours: "24 ساعة",
      crowdLevel: "متوسط",
    },
    {
      id: "pharmacy-emergency",
      name: "صيدلية الطوارئ - الأدوية الأساسية",
      description: "صيدلية طوارئ للحالات العاجلة والأدوية الأساسية",
      distance: 0,
      direction: "",
      lat: 24.468,
      lng: 39.6118,
      floor: "الدور الأرضي",
      capacity: "خدمة سريعة",
      features: ["طوارئ", "سريعة", "أدوية أساسية"],
      openingHours: "24 ساعة",
      crowdLevel: "منخفض",
    },
  ],

  "مواقف السيارات": [
    {
      id: "parking-east",
      name: "موقف السيارات الشرقي - موقف رق�� 1",
      description: "موقف كبير مع تكييف ومراقبة أمنية",
      distance: 0,
      direction: "",
      lat: 24.47,
      lng: 39.615,
      floor: "متعدد الطوابق",
      capacity: "2000 سيارة",
      features: ["مكيف", "مراقبة أمنية", "مجاني"],
      openingHours: "24 ساعة",
      crowdLevel: "مرتفع",
    },
    {
      id: "parking-west",
      name: "موقف السيارات الغربي - موقف رقم 2",
      description: "موقف واسع مع خدمات إضافية ومحطة غسيل",
      distance: 0,
      direction: "",
      lat: 24.466,
      lng: 39.607,
      floor: "متعدد الطوابق",
      capacity: "1500 سيارة",
      features: ["محطة غسيل", "خدمات إضافية", "مجاني"],
      openingHours: "24 ساعة",
      crowdLevel: "متوسط",
    },
    {
      id: "parking-buses",
      name: "موقف الحافلات - محطة النقل",
      description: "موقف مخصص للحافلات والنقل الجماعي",
      distance: 0,
      direction: "",
      lat: 24.464,
      lng: 39.611,
      floor: "الدور الأرضي",
      capacity: "100 حافلة",
      features: ["نقل جماعي", "محطة رئيسية", "مجاني"],
      openingHours: "24 ساعة",
      crowdLevel: "مرتفع",
    },
  ],

  "أماكن الراحة": [
    {
      id: "rest-main",
      name: "صالة الراحة الرئيسية - الدور الأول",
      description: "صالة كبيرة مكيفة مع مقاعد مريحة وخدمات متنوعة",
      distance: 0,
      direction: "",
      lat: 24.469,
      lng: 39.6115,
      floor: "الدور الأول",
      capacity: "300 شخص",
      features: ["مكيفة", "مقاعد مريحة", "خدمات متنوعة"],
      openingHours: "24 ساعة",
      crowdLevel: "مرتفع",
    },
    {
      id: "rest-family",
      name: "منطقة الراحة العائلية - قسم العوائل",
      description: "منطقة هادئة مخصصة للعائلات مع مرافق أطفال",
      distance: 0,
      direction: "",
      lat: 24.467,
      lng: 39.6105,
      floor: "الدور الأول",
      capacity: "150 شخص",
      features: ["مخصصة للعائلات", "مرافق أطفال", "هادئة"],
      openingHours: "24 ساعة",
      crowdLevel: "متوسط",
    },
    {
      id: "rest-ac",
      name: "مكان الراحة المكيف - منطقة الصمت",
      description: "منطقة راحة هادئة جداً مع تكييف قوي",
      distance: 0,
      direction: "",
      lat: 24.468,
      lng: 39.6122,
      floor: "الدور الثاني",
      capacity: "100 شخص",
      features: ["هادئة جداً", "تكييف قوي", "مريحة"],
      openingHours: "24 ساعة",
      crowdLevel: "منخفض",
    },
  ],

  "مراكز الطوارئ الطبية": [
    {
      id: "medical-main",
      name: "مركز الطوارئ الطبية الرئيسي",
      description: "مركز طبي متكامل مع أطباء متخصصين وإسعافات أولية",
      distance: 0,
      direction: "",
      lat: 24.4675,
      lng: 39.6112,
      floor: "الدور الأرضي",
      capacity: "50 سرير",
      features: ["أطباء متخصصين", "إسعافات أولية", "معدات حديثة"],
      openingHours: "24 ساعة",
      crowdLevel: "حسب الحاجة",
    },
    {
      id: "medical-mobile",
      name: "العيادة الطبية المتنقلة",
      description: "عيادة متنقلة للحالات ��لبسيطة والفحوصات السريعة",
      distance: 0,
      direction: "",
      lat: 24.468,
      lng: 39.6115,
      floor: "متنقلة",
      capacity: "10 أشخاص",
      features: ["متنقلة", "فحوصات سريعة", "حالات بسيطة"],
      openingHours: "24 ساعة",
      crowdLevel: "منخفض",
    },
  ],

  "مكاتب المفقودات": [
    {
      id: "lost-main",
      name: "مكتب المفقودات الرئيسي - الدور الأرضي",
      description: "مكتب رئيسي للإبلاغ عن المفقودات واستردادها",
      distance: 0,
      direction: "",
      lat: 24.4678,
      lng: 39.6113,
      floor: "الدور الأرضي",
      capacity: "خدمة مستمرة",
      features: ["خدمة شاملة", "سجلات دقيقة", "استرداد سريع"],
      openingHours: "24 ساعة",
      crowdLevel: "متوسط",
    },
    {
      id: "lost-secondary",
      name: "مكتب المفقودات الفرعي - الدور الأول",
      description: "مكتب فرعي للحالات البسيطة والاستفسارات السريعة",
      distance: 0,
      direction: "",
      lat: 24.467,
      lng: 39.6107,
      floor: "الدور الأول",
      capacity: "خدمة سريعة",
      features: ["حالات بسيطة", "استفسارات سريعة", "فرعي"],
      openingHours: "24 ساعة",
      crowdLevel: "منخفض",
    },
  ],

  "أماكن الهدايا والتذكارات": [
    {
      id: "gifts-islamic",
      name: "متجر الهدايا الإسلامية - المجموعة الذهبية",
      description: "متجر يضم أجمل الهدايا الإسلامية والمصاحف الشريفة",
      distance: 0,
      direction: "",
      lat: 24.469,
      lng: 39.6118,
      floor: "الدور الأول",
      capacity: "50 شخص",
      features: ["هدايا إسلامية", "مصاحف شريفة", "جودة عالية"],
      openingHours: "08:00 - 23:00",
      crowdLevel: "مرتفع",
    },
    {
      id: "gifts-souvenirs",
      name: "متجر التذكارات - ذكريات المدينة",
      description: "متجر تذكارات يضم منتجات تراثية من المدينة المنورة",
      distance: 0,
      direction: "",
      lat: 24.468,
      lng: 39.611,
      floor: "الدور الأرضي",
      capacity: "30 شخص",
      features: ["منتجات تراثية", "تذكارات", "أسعار مناسبة"],
      openingHours: "08:00 - 23:00",
      crowdLevel: "متوسط",
    },
  ],

  "خدمات الترجمة": [
    {
      id: "translation-main",
      name: "مكتب الترجمة الرئيسي - خدمات شاملة",
      description: "مكتب ترجمة شامل يخدم أكثر من 20 لغة",
      distance: 0,
      direction: "",
      lat: 24.4682,
      lng: 39.6115,
      floor: "الدور الأول",
      capacity: "10 مترجمين",
      features: ["20+ لغة", "مترجمين محترفين", "خدمة شاملة"],
      openingHours: "24 ساعة",
      crowdLevel: "مرتفع",
    },
    {
      id: "translation-mobile",
      name: "مترجمين متنقلين - خدمة ميدانية",
      description: "فريق مترجمين متنقلين لمساعدة الحجاج في جميع أنحاء المسجد",
      distance: 0,
      direction: "",
      lat: 24.4675,
      lng: 39.6108,
      floor: "متنقل",
      capacity: "5 مترجمين",
      features: ["متنقلين", "خدمة ميدانية", "لغات متعددة"],
      openingHours: "24 ساعة",
      crowdLevel: "متوسط",
    },
  ],

  "مراكز الاستعلامات": [
    {
      id: "info-main",
      name: "مركز الاستعلامات الرئيسي - المعلومات الشاملة",
      description: "مركز معلومات شامل مع جميع ا��تفاصيل عن المسجد والخدمات",
      distance: 0,
      direction: "",
      lat: 24.4685,
      lng: 39.6115,
      floor: "الدور الأرضي",
      capacity: "خدمة مستمرة",
      features: ["معلومات شاملة", "خرائط", "برامج إرشادية"],
      openingHours: "24 ساعة",
      crowdLevel: "مرتفع",
    },
    {
      id: "info-mobile",
      name: "نقطة الاستعلامات المتنقلة - خدمة سريعة",
      description: "نقطة استعلامات متنقلة للأسئلة السريعة والتوجيه الفوري",
      distance: 0,
      direction: "",
      lat: 24.467,
      lng: 39.611,
      floor: "متنقلة",
      capacity: "خدمة سريعة",
      features: ["خدمة سريعة", "متنقلة", "توجيه فوري"],
      openingHours: "24 ساعة",
      crowdLevel: "متوسط",
    },
  ],
};

// Updated type definition to include new fields
declare module "@/types/dlni" {
  interface Location {
    id?: string;
    floor?: string;
    capacity?: string;
    features?: string[];
    openingHours?: string;
    crowdLevel?: string;
  }
}

export const duasData: Record<ServiceType, string> = {
  "دورات المياه": "اللهم إني أعوذ بك من الخبث والخبائث",
  "أماكن الوضوء": "اللهم اجعلني من التوابين واجعلني من المتطهرين",
  "الروضة الشريفة": "اللهم صل وسلم على نبينا محمد وعلى آله وصحبه أجمعين",
  "مياه زمزم": "اللهم إنه بلغني أن رسولك قال: ماء زمزم لما شرب له",
  الطواف: "ربنا آتنا في الدنيا حسنة وفي الآخرة حسنة وقنا عذاب النار",
  السعي:
    "إن الصفا والمروة من شعائر الله فمن حج البيت أو اعتمر فلا جناح عليه أن يطوف بهما",
  الحلاقة: "اللهم بارك لنا فيما أعطيت",
  "مكاتب الإرشاد": "اللهم أرني الحق حقاً وارزقني اتباعه",
  "مكاتب الأمانات": "اللهم احفظ أماناتنا وأماناتهم",
  "مخارج الطوارئ": "اللهم سلمنا وسلم المسلمين",
  "ذوي الاحتياجات الخاصة": "اللهم عافني في بدني واجعلني من الشاكرين",
  "المط��عم والكافيتريات": "بسم الله نبدأ وعلى بركة الله نأكل",
  الصيدليات: "اللهم اشفني واشف مرضى المسلمين",
  "مواقف السيارات": "اللهم بارك لنا فيما رزقتنا",
  "أماكن الراحة": "الحمد لله الذي أطعمنا وسقانا وآوانا",
  "مراكز الطوارئ الطبية": "اللهم اشفني واشف مرضى المسلمين أجمعين",
  "مكاتب المفقودات": "اللهم رد علينا ضالتنا",
  "أماكن الهدايا والتذكارات": "اللهم بارك لنا فيما اشترينا",
  "خدمات الترجمة": "اللهم علمنا ما ينفعنا وانفعنا بما علمتنا",
  "مراكز الاستعلامات": "اللهم أرني الحق حقاً وارزقني اتباعه",
};

export const chatResponses: Record<string, string> = {
  "أين أقرب دورة مياه؟":
    "بناءً على موقعك الحالي، سأوضح لك أقرب دورة مياه مع المسافة الدقيقة. يوجد 6 دورات مياه متوفرة في المسجد موزعة على جميع الأدوار.",
  "كيف أصل للروضة الشريفة؟":
    "سأرشدك إلى الروضة الشريفة بناءً على موقعك الحالي. يرجى ملاحظة أن الدخول محدود بأوقات معينة ويتطلب تنظيماً خاصاً.",
  "أين مياه زمزم؟":
    "سأدلك على أقرب مكان لمياه زمزم من موقعك الحالي. يوجد مصدر رئيسي في القبو ونقاط توزيع فرعية.",
  "مواقيت الصلاة":
    "مواقيت الصلاة اليوم:\nالفجر: 5:15\nالظهر: 12:30\nالعصر: 3:45\nالمغرب: 6:20\nالعشاء: 7:50\nتحديث مستمر متوفر في تطبيق دلّني.",
  "كيف أبدأ الطواف؟":
    "سأرشدك إلى أقرب مدخل للطواف من موقعك الحالي. يوجد مدخل رئيسي ومدخل مخصص للمعاقين.",
  "أين أجد مكان السعي؟":
    "سأوضح لك أقرب نقطة لبدء السعي من موقعك. يبدأ المسار من الصفا مع نقاط راحة متوفرة.",
  "أين يمكنني الحلاقة؟":
    "سأدلك على أقرب محل حلاقة من موقعك الحالي. يوجد محلان للرجال ومحل مخصص للنساء.",
  "أحتاج مساعدة طبية":
    "سأرشدك إلى أقرب مركز طبي من موقعك. للطوارئ: 997. يوجد مركز رئيسي وعيادة متنقلة.",
  "أين المطاعم؟":
    "سأوضح لك أقرب المطاعم والكافيتريات. يوجد مطعم الحرمين وكافيتريا الضيافة ومقهى المدينة.",
  "أين أحفظ أمتعتي؟":
    "سأرشدك إلى أقرب مكتب أمانات. يوجد مكتب رئيسي و فرعي آمنين مع مراقبة 24/7.",
  "أين المواقف؟":
    "سأدلك على أقرب موقف سيارات. يوجد موقف شرقي وغربي وموقف مخصص للحافلات.",
  "خدمات المعاقين":
    "سأرشدك إلى المرافق المخصصة لذوي الاحتياجات الخاصة مع المصاعد والمرافق الخاصة.",
};
